release 3.6.0
IN-CORE/incore-data-release pull request #34
Opened 2022-09-12 19:50 UTC by ywkim312

2022-09-12 20:09 UTC, longshuicy requested changes
need to merge against main?

2022-09-12 20:10 UTC, ywkim312 commented
> need to merge against main?

oops changed.... thanks for catching it

2022-09-12 21:34 UTC, longshuicy approved these changes

2022-09-13 12:48 UTC, nunezco2 approved these changes

2022-09-14 20:28 UTC, merged